---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
setwd("/Users/utamhank/Desktop/DataScience/Reproducible Research/P1")
df <- read.csv("activity.csv")
df1 <- df[!is.na(df$steps),]
totalsteps <- tapply(df1$steps, df1$date, sum)
totalsteps1 <- totalsteps[!is.na(totalsteps)]
```

## Histogram of total number of steps taken each day
```{r}
hist(totalsteps1, main ="histogram with missing values removed", xlab ="total daily steps")
```

## What is mean total number of steps taken per day?
```{r}
m1 <- mean(totalsteps1)
print(m1)

```

## what is the median number of steps taken per day
```{r}
median(totalsteps1)

```

## What is the average daily activity pattern?

```{r}
avgintervalsteps <- tapply(df1$steps, df1$interval, mean)
plot(avgintervalsteps, xlab="interval", ylab="average steps", type="l")
```

## Imputing missing values

```{r}
df2  <- as.data.frame(totalsteps)
count <- nrow(df2[is.na(df2$totalsteps),])
print(count)
df2$totalsteps[is.na(df2$totalsteps)] <- rep(c(m1), count)
hist(df2$totalsteps, main="histogram with imputed values", xlab ="average daily steps")
```

## Are there differences in activity patterns between weekdays and weekends?
